name: Ai-summarizer Pipeline
 
on:

  push:

    branches: [ main ]

  pull_request:

    branches: [ main ]
 
jobs:

  build-and-deploy:

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout code

        uses: actions/checkout@v3
 
      - name: Set up JDK 21

        uses: actions/setup-java@v3

        with:

          distribution: 'temurin'

          java-version: '21'

          java-package: 'jdk'

          check-latest: false

          server-id: github

          server-username: ${{ github.actor }}

          server-password: ${{ secrets.GITHUB_TOKEN }}

          overwrite-settings: true
 
      - name: Build with Maven (skip tests)

        run: mvn clean install -DskipTests
 
      - name: Build Docker image

        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ai-summarizer .
 
      - name: Login to DockerHub

        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
      - name: Push Docker image

        run: docker push ${{ secrets.DOCKER_USERNAME }}/ai-summarizer
